// <auto-generated />
namespace LMS.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class Courses_and_Modules : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Courses_and_Modules));
        
        string IMigrationMetadata.Id
        {
            get { return "201711271031386_Courses_and_Modules"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
